/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Default)]
pub struct __IncompleteArrayField<T>(::std::marker::PhantomData<T>, [T; 0]);
impl<T> __IncompleteArrayField<T> {
    #[inline]
    pub const fn new() -> Self {
        __IncompleteArrayField(::std::marker::PhantomData, [])
    }
    #[inline]
    pub fn as_ptr(&self) -> *const T {
        self as *const _ as *const T
    }
    #[inline]
    pub fn as_mut_ptr(&mut self) -> *mut T {
        self as *mut _ as *mut T
    }
    #[inline]
    pub unsafe fn as_slice(&self, len: usize) -> &[T] {
        unsafe { ::std::slice::from_raw_parts(self.as_ptr(), len) }
    }
    #[inline]
    pub unsafe fn as_mut_slice(&mut self, len: usize) -> &mut [T] {
        unsafe { ::std::slice::from_raw_parts_mut(self.as_mut_ptr(), len) }
    }
}
impl<T> ::std::fmt::Debug for __IncompleteArrayField<T> {
    fn fmt(&self, fmt: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        fmt.write_str("__IncompleteArrayField")
    }
}
pub const DM_DIR: &[u8; 7] = b"mapper\0";
pub const DM_CONTROL_NODE: &[u8; 8] = b"control\0";
pub const DM_MAX_TYPE_NAME: u32 = 16;
pub const DM_NAME_LEN: u32 = 128;
pub const DM_UUID_LEN: u32 = 129;
pub const DM_NAME_LIST_FLAG_HAS_UUID: u32 = 1;
pub const DM_NAME_LIST_FLAG_DOESNT_HAVE_UUID: u32 = 2;
pub const DM_IOCTL: u32 = 253;
pub const DM_VERSION_MAJOR: u32 = 4;
pub const DM_VERSION_MINOR: u32 = 45;
pub const DM_VERSION_PATCHLEVEL: u32 = 0;
pub const DM_VERSION_EXTRA: &[u8; 20] = b"-ioctl (2021-03-22)\0";
pub const DM_READONLY_FLAG: u32 = 1;
pub const DM_SUSPEND_FLAG: u32 = 2;
pub const DM_PERSISTENT_DEV_FLAG: u32 = 8;
pub const DM_STATUS_TABLE_FLAG: u32 = 16;
pub const DM_ACTIVE_PRESENT_FLAG: u32 = 32;
pub const DM_INACTIVE_PRESENT_FLAG: u32 = 64;
pub const DM_BUFFER_FULL_FLAG: u32 = 256;
pub const DM_SKIP_BDGET_FLAG: u32 = 512;
pub const DM_SKIP_LOCKFS_FLAG: u32 = 1024;
pub const DM_NOFLUSH_FLAG: u32 = 2048;
pub const DM_QUERY_INACTIVE_TABLE_FLAG: u32 = 4096;
pub const DM_UEVENT_GENERATED_FLAG: u32 = 8192;
pub const DM_UUID_FLAG: u32 = 16384;
pub const DM_SECURE_DATA_FLAG: u32 = 32768;
pub const DM_DATA_OUT_FLAG: u32 = 65536;
pub const DM_DEFERRED_REMOVE: u32 = 131072;
pub const DM_INTERNAL_SUSPEND_FLAG: u32 = 262144;
pub const DM_IMA_MEASUREMENT_FLAG: u32 = 524288;
pub const _IOC_NRBITS: u32 = 8;
pub const _IOC_TYPEBITS: u32 = 8;
pub const _IOC_SIZEBITS: u32 = 14;
pub const _IOC_DIRBITS: u32 = 2;
pub const _IOC_NRMASK: u32 = 255;
pub const _IOC_TYPEMASK: u32 = 255;
pub const _IOC_SIZEMASK: u32 = 16383;
pub const _IOC_DIRMASK: u32 = 3;
pub const _IOC_NRSHIFT: u32 = 0;
pub const _IOC_TYPESHIFT: u32 = 8;
pub const _IOC_SIZESHIFT: u32 = 16;
pub const _IOC_DIRSHIFT: u32 = 30;
pub const _IOC_NONE: u32 = 0;
pub const _IOC_WRITE: u32 = 1;
pub const _IOC_READ: u32 = 2;
pub type __s32 = ::std::os::raw::c_int;
pub type __u32 = ::std::os::raw::c_uint;
pub type __u64 = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dm_ioctl {
    pub version: [__u32; 3usize],
    pub data_size: __u32,
    pub data_start: __u32,
    pub target_count: __u32,
    pub open_count: __s32,
    pub flags: __u32,
    pub event_nr: __u32,
    pub padding: __u32,
    pub dev: __u64,
    pub name: [::std::os::raw::c_char; 128usize],
    pub uuid: [::std::os::raw::c_char; 129usize],
    pub data: [::std::os::raw::c_char; 7usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dm_ioctl"][::std::mem::size_of::<dm_ioctl>() - 312usize];
    ["Alignment of dm_ioctl"][::std::mem::align_of::<dm_ioctl>() - 8usize];
    ["Offset of field: dm_ioctl::version"][::std::mem::offset_of!(dm_ioctl, version) - 0usize];
    ["Offset of field: dm_ioctl::data_size"][::std::mem::offset_of!(dm_ioctl, data_size) - 12usize];
    ["Offset of field: dm_ioctl::data_start"]
        [::std::mem::offset_of!(dm_ioctl, data_start) - 16usize];
    ["Offset of field: dm_ioctl::target_count"]
        [::std::mem::offset_of!(dm_ioctl, target_count) - 20usize];
    ["Offset of field: dm_ioctl::open_count"]
        [::std::mem::offset_of!(dm_ioctl, open_count) - 24usize];
    ["Offset of field: dm_ioctl::flags"][::std::mem::offset_of!(dm_ioctl, flags) - 28usize];
    ["Offset of field: dm_ioctl::event_nr"][::std::mem::offset_of!(dm_ioctl, event_nr) - 32usize];
    ["Offset of field: dm_ioctl::padding"][::std::mem::offset_of!(dm_ioctl, padding) - 36usize];
    ["Offset of field: dm_ioctl::dev"][::std::mem::offset_of!(dm_ioctl, dev) - 40usize];
    ["Offset of field: dm_ioctl::name"][::std::mem::offset_of!(dm_ioctl, name) - 48usize];
    ["Offset of field: dm_ioctl::uuid"][::std::mem::offset_of!(dm_ioctl, uuid) - 176usize];
    ["Offset of field: dm_ioctl::data"][::std::mem::offset_of!(dm_ioctl, data) - 305usize];
};
impl Default for dm_ioctl {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct dm_target_spec {
    pub sector_start: __u64,
    pub length: __u64,
    pub status: __s32,
    pub next: __u32,
    pub target_type: [::std::os::raw::c_char; 16usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dm_target_spec"][::std::mem::size_of::<dm_target_spec>() - 40usize];
    ["Alignment of dm_target_spec"][::std::mem::align_of::<dm_target_spec>() - 8usize];
    ["Offset of field: dm_target_spec::sector_start"]
        [::std::mem::offset_of!(dm_target_spec, sector_start) - 0usize];
    ["Offset of field: dm_target_spec::length"]
        [::std::mem::offset_of!(dm_target_spec, length) - 8usize];
    ["Offset of field: dm_target_spec::status"]
        [::std::mem::offset_of!(dm_target_spec, status) - 16usize];
    ["Offset of field: dm_target_spec::next"]
        [::std::mem::offset_of!(dm_target_spec, next) - 20usize];
    ["Offset of field: dm_target_spec::target_type"]
        [::std::mem::offset_of!(dm_target_spec, target_type) - 24usize];
};
#[repr(C)]
#[derive(Debug, Default)]
pub struct dm_name_list {
    pub dev: __u64,
    pub next: __u32,
    pub name: __IncompleteArrayField<::std::os::raw::c_char>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dm_name_list"][::std::mem::size_of::<dm_name_list>() - 16usize];
    ["Alignment of dm_name_list"][::std::mem::align_of::<dm_name_list>() - 8usize];
    ["Offset of field: dm_name_list::dev"][::std::mem::offset_of!(dm_name_list, dev) - 0usize];
    ["Offset of field: dm_name_list::next"][::std::mem::offset_of!(dm_name_list, next) - 8usize];
    ["Offset of field: dm_name_list::name"][::std::mem::offset_of!(dm_name_list, name) - 12usize];
};
pub const DM_VERSION_CMD: _bindgen_ty_1 = 0;
pub const DM_REMOVE_ALL_CMD: _bindgen_ty_1 = 1;
pub const DM_LIST_DEVICES_CMD: _bindgen_ty_1 = 2;
pub const DM_DEV_CREATE_CMD: _bindgen_ty_1 = 3;
pub const DM_DEV_REMOVE_CMD: _bindgen_ty_1 = 4;
pub const DM_DEV_RENAME_CMD: _bindgen_ty_1 = 5;
pub const DM_DEV_SUSPEND_CMD: _bindgen_ty_1 = 6;
pub const DM_DEV_STATUS_CMD: _bindgen_ty_1 = 7;
pub const DM_DEV_WAIT_CMD: _bindgen_ty_1 = 8;
pub const DM_TABLE_LOAD_CMD: _bindgen_ty_1 = 9;
pub const DM_TABLE_CLEAR_CMD: _bindgen_ty_1 = 10;
pub const DM_TABLE_DEPS_CMD: _bindgen_ty_1 = 11;
pub const DM_TABLE_STATUS_CMD: _bindgen_ty_1 = 12;
pub const DM_LIST_VERSIONS_CMD: _bindgen_ty_1 = 13;
pub const DM_TARGET_MSG_CMD: _bindgen_ty_1 = 14;
pub const DM_DEV_SET_GEOMETRY_CMD: _bindgen_ty_1 = 15;
pub const DM_DEV_ARM_POLL_CMD: _bindgen_ty_1 = 16;
pub const DM_GET_TARGET_VERSION_CMD: _bindgen_ty_1 = 17;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
