[workspace]
members = ["libssam", "ssamd", "proc_macros", "ssam", "ssam-wrap", "quotactl-rs", "ssam-log"]
exclude = ["testdata"]
resolver = "2"

[workspace.dependencies]
libssam = { path = "libssam" }
proc_macros = { path = "proc_macros" }
ssam-log = { path = "ssam-log" }
bincode = { version = "2.0.1", features = ["serde", "derive"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = { version = "1.0.117", features = ["preserve_order"] }
serde-big-array = "0.5.1"
thiserror = "2.0"
simplelog = { version = "0.12.2", default-features = false }
log = "0.4.21"
rsa = { version = "0.9.6", features = ["sha2"] }
clap = { version = "4.5.17", features = ["derive"] }
strum = { version = "0.28", features = ["derive"] }
strum_macros = "0.28"
anyhow = "1.0.86"
tonic = "0.14"
prost = "0.14"
prost-types = "0.14"
toml = "1.1"
quote = "1.0.37"
syn = { version = "2.0.87", features = ["full"] }
proc-macro2 = "1.0.89"
itertools = "0.14"
oci-spec = { version = "0.9", features = [
    "runtime",
], default-features = false }
tokio = "1.45"
derive_more = { version = "2.0", features = ["deref"] }
linux-raw-sys = "0.12"
tempfile = "3.15.0"
semver = "1.0.26"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "Apache-2.0"
description = "SSAM runs container-native apps using the OCI Runtime standard"
repository = "https://github.com/mobis-oss/ssam"
authors = [
    "jooyoung.jung@mobis.com",
    "kwanhong.lee@mobis.com",
    "youhyun.jung@mobis.com",
]
keywords = ["containers", "oci", "embedded", "automotive", "linux"]
categories = ["os", "command-line-utilities"]
