load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library")

rust_library(
    name = "ssamd_lib",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/main.rs"],
    ),
    crate_name = "ssamd",
    crate_features = ["dm-verity"],
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        "//libssam:libssam",
        "//quotactl-rs:quotactl-rs",
        "//ssam-log:ssam-log",
        "@crates//:anyhow",
        "@crates//:bincode",
        "@crates//:cgroups-rs",
        "@crates//:derive_more",
        "@crates//:futures-util",
        "@crates//:libc",
        "@crates//:linux-raw-sys",
        "@crates//:log",
        "@crates//:loopdev-3",
        "@crates//:oci-spec",
        "@crates//:once_cell",
        "@crates//:procfs",
        "@crates//:prost-types",
        "@crates//:rsactor",
        "@crates//:rustix",
        "@crates//:sd-notify",
        "@crates//:semver",
        "@crates//:serde",
        "@crates//:serde-big-array",
        "@crates//:serde_json",
        "@crates//:simplelog",
        "@crates//:strum",
        "@crates//:tempfile",
        "@crates//:thiserror",
        "@crates//:tokio",
        "@crates//:tokio-stream",
        "@crates//:tokio-util",
        "@crates//:toml",
        "@crates//:tonic",
        "@crates//:uuid",
        "@crates//:zbus",
        "@crates//:zbus_systemd",
    ],
    proc_macro_deps = [
        "@crates//:async-trait",
        "@crates//:strum_macros",
    ],
)

rust_binary(
    name = "ssamd",
    srcs = ["src/main.rs"],
    edition = "2024",
    visibility = ["//visibility:public"],
    deps = [
        ":ssamd_lib",
        "@crates//:anyhow",
    ],
)
