[package]
name = "ssamd"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "ssamd"
path = "src/lib.rs"

[[bin]]
name = "ssamd"
path = "src/main.rs"

[features]
default = ["dm-verity"]
dm-verity = []
profile = []

[dependencies]
libssam.workspace = true
ssam-log.workspace = true
simplelog.workspace = true
tokio = { workspace = true, features = [
    "macros",
    "signal",
    "rt",
    "rt-multi-thread",
] }
zbus = { version = "5.7", default-features = false, features = ["tokio"] }
zbus_systemd = { version = "0.26000", features = ["systemd1"] }
futures-util = "0.3.30"
sd-notify = "0.5"
log.workspace = true
loopdev-3 = "0.5.1"
anyhow.workspace = true
serde.workspace = true
serde-big-array.workspace = true
bincode.workspace = true
tonic.workspace = true
async-trait = "0.1.83"
strum.workspace = true
strum_macros.workspace = true
once_cell = "1.20.2"
tempfile.workspace = true
rustix = { version = "1.0.3", features = ["mount", "time"] }
quotactl-rs = { path = "../quotactl-rs" }
thiserror.workspace = true
linux-raw-sys = { workspace = true, features = ["loop_device"] }
procfs = "0.18"
oci-spec.workspace = true
cgroups-rs = "0.5"
tokio-stream = { version = "0.1.17", features = ["fs"] }
rsactor = "0.15"
derive_more.workspace = true
tokio-util = "0.7.15"
semver.workspace = true
toml.workspace = true
serde_json.workspace = true
prost-types.workspace = true
uuid = { version = "1", features = ["v4", "fast-rng"] }

[dev-dependencies]
mockall = "0.14"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(coverage,coverage_nightly)',
] }
