load("@rules_rust//rust:defs.bzl", "rust_proc_macro")

rust_proc_macro(
    name = "proc_macros",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    edition = "2024",
    deps = [
        "@crates//:heck",
        "@crates//:proc-macro2",
        "@crates//:quote",
        "@crates//:syn",
        "@crates//:toml",
    ],
    visibility = ["//visibility:public"],
)
